name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Clonado completo para mejorar el análisis en SonarCloud

      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Paso 3: Instalar dependencias de Node.js
      - name: Instalar dependencias de Node.js
        run: |
          npm install

      # Paso 4: Ejecutar pruebas con cobertura
      - name: Ejecutar pruebas y generar cobertura
        run: |
          npm run test:cov

      # Paso 5: Escaneo de SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Para obtener info de PRs, si existe
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.verbose=true
